### PR TITLE
Fixed import to support Django>=1.9.

### PR DESCRIPTION
**Pull request by chrisspen**

### CODE REVIEW

**Comment by kennedyshead** [comment]
This should be merged, however it should be split in 2. One for the travis fix and one for django

**Comment by kennedyshead** [comment]
It also fixes the header issue in gevent-1.1.0

**Comment by kennedyshead** [comment]
+1 for this merge

**Comment by abourget** [comment]
@kennedyshead thanks for going through those things.. I gave you write access. would manage an eventual release ?  I'd be very pleased if you wanted to do this.  To increase trust with the community, maybe you want to update your profile with your picture and full name :)

**Comment by kennedyshead** [comment]
:) I will do that asap. I can manage an eventual release (have a busy schedule, but I'll manage)

**Comment by chrisspen** [comment]
Thanks!

**Pull request merged**
